### ISSUE TITLE
关于噪声标签如何过滤

### ISSUE THREAD

**Issue by PunkMale** [qinxiaoyi/Simple-Attention-Module-based-Speaker-Verification-with-Iterative-Noisy-Label-Detection#2]
您好！
关于您的论文中噪声标签的清理过程我的理解是：
对于某个样本（`目标样本`），我们计算`对应说话人`的所有样本（除了目标样本外）的`平均embedding`，然后计算`目标样本embedding`和这个`平均embedding`之间的`cosine相似度`是否超过`预设阈值`。超过阈值则为干净，否则是噪声。
请问我的理解是否正确？

**Comment by qinxiaoyi** [comment]
您好，您的理解是正确的并且是通用的，不同的在于这篇论文针对voxceleb做了特别的设计。由于VoxCeleb的数据组成形式为：
说话人(spk id)/视频段(segment id)/音频片段(utterance id)，所以在计算cosine相似度的时候是目标样本embedding和该说话人平均embeding（除了目标样本所在segment之外所有音频）之间的cosine相似度。其余的完全正确。

这种设计的考量是考虑到人脸识别可能错误，导致整个segment的音频都不是目标说话人。

**Comment by PunkMale** [comment]
了解了。非常感谢您的分享！
祝您科研顺利！😊
